trigger:
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
    steps:
    - bash: |
          echo "hi"
          id
          echo "Checking Default python version"
          python --version
          echo "Setting python3"
          set PYTHONPATH=/usr/bin/python3
          python --version
          

         

      
