trigger:
   
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
   
    steps:
    - task: Bash@3
      inputs:
        filePath: '/usr/bin/python3'
        bashEnvValue: '/usr/bin/python3'
    
    - script: |
          echo "hi"
          id
          echo "Checking Default python version"
          python --version
          echo $(PYTHONPATH)

            
        
          

         

      
