trigger:
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
    steps:
    - bash: |
          echo "hi"
          id
          echo "Checking Default python version"
          python --version

          echo "Checking python version"
          alias python='/usr/bin/python3'
          alias python3='/usr/bin/python3'
          python --version

      
