trigger:
   
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
   
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
       versionSpec: 3.8
       githubToken: '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'
       addToPath: true
       architecture: 'x64'
    - bash: |
            echo "alias python=/usr/bin/python3" > BASH_ENV
            
            source "BASH_ENV"
            python --version
           

            
        
          

         

      
