trigger:
   
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
    steps:
    
     - bash: |
          echo "hi"
          id
          echo "Checking Default python version"
          python --version
          echo "Setting python3"
          echo "alias python='/usr/bin/python3'" > script.sh
          echo "alias python3='/usr/bin/python3'" >> script.sh
          sudo chmod +x script.sh
          bash script.sh
         
         
          python --version
   
            
        
          

         

      
