trigger:
   
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
   
    steps:
    - bash: |
            echo "alias python=/usr/bin/python3" > BASH_ENV
            
            source "BASH_ENV"
            python --version
            python3 --version

            
        
          

         

      
