trigger:
   
- main



stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool: demo
    strategy:
      matrix:
        Python37: 
          python.version: '3.7'
    steps:
    - task:  UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
          echo "hi"
          id
          echo "Checking Default python version"
          python --version
          echo "Setting python3"
          alias python='/usr/bin/python3'
          alias python3='/usr/bin/python3'
                
          python --version
   
            
        
          

         

      
